[package]
name = "gautrain"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argh = "0.1.13"
csv = "1.3.1"
dateparser = "0.2.1"
dialoguer = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
